name: Docker Flask Deploy

on:
    workflow_dispatch: 

jobs:
    deploy:

        runs-on: self-hosted
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        steps:
            - name: Code checkout
              uses: actions/checkout@v5

            - name: Pull image from DockerHub
              run: docker compose pull

            - name: Deploy with docker compose
              run: docker compose up -d --build

            - name: Check running containers
              run: docker ps