name: Docker Build & push

on:
    push:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout
              uses: actions/checkout@v5
            
            - name: Login to DockerHub
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USER}}
                password: ${{ secrets.DOCKERHUB_PASS}}

            - name: Docker build
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: | 
                    ${{ vars.DOCKERHUB_USER}}/python-todo-app:latest
                    ${{ vars.DOCKERHUB_USER}}/github-action-app:${{ github.head_ref }}
                    ${{ vars.DOCKERHUB_USER}}/${{ github.event.repository.name }}:${{ github.sha }}